/** AskX 本地图标支持的分类。 */
export const askxIconCategories = ['actions', 'navigation', 'status', 'objects', 'platforms'] as const

/** AskX 本地图标分类。 */
export type AskxIconCategory = typeof askxIconCategories[number]

/** AskX 本地图标分类的展示名称。 */
export const askxIconCategoryLabels: Record<AskxIconCategory, string> = {
  actions: '操作',
  navigation: '导航',
  status: '状态',
  objects: '对象',
  platforms: '平台',
}

/** AskX 项目当前可用的本地图标清单。 */
export const askxIconCatalog = [
  { name: 'askx-actions:add', category: 'actions' },
  { name: 'askx-actions:remove', category: 'actions' },
  { name: 'askx-actions:close', category: 'actions' },
  { name: 'askx-actions:copy', category: 'actions' },
  { name: 'askx-actions:delete', category: 'actions' },
  { name: 'askx-actions:erase', category: 'actions' },
  { name: 'askx-actions:edit', category: 'actions' },
  { name: 'askx-actions:preview', category: 'actions' },
  { name: 'askx-actions:hide', category: 'actions' },
  { name: 'askx-actions:refresh', category: 'actions' },
  { name: 'askx-actions:undo', category: 'actions' },
  { name: 'askx-actions:redo', category: 'actions' },
  { name: 'askx-actions:settings', category: 'actions' },
  { name: 'askx-actions:external-link', category: 'actions' },
  { name: 'askx-actions:confirm', category: 'actions' },
  { name: 'askx-actions:adjust', category: 'actions' },
  { name: 'askx-actions:crop', category: 'actions' },
  { name: 'askx-actions:download', category: 'actions' },
  { name: 'askx-actions:upload', category: 'actions' },
  { name: 'askx-actions:send', category: 'actions' },
  { name: 'askx-actions:more', category: 'actions' },
  { name: 'askx-actions:search', category: 'actions' },
  { name: 'askx-actions:help', category: 'actions' },
  { name: 'askx-actions:sparkle', category: 'actions' },
  { name: 'askx-actions:stop', category: 'actions' },
  { name: 'askx-actions:expand', category: 'actions' },
  { name: 'askx-actions:play', category: 'actions' },
  { name: 'askx-actions:pause', category: 'actions' },
  { name: 'askx-actions:add-agent', category: 'actions' },
  { name: 'askx-actions:auto-select', category: 'actions' },
  { name: 'askx-actions:batch-edit', category: 'actions' },
  { name: 'askx-actions:bold', category: 'actions' },
  { name: 'askx-actions:brush', category: 'actions' },
  { name: 'askx-actions:compare', category: 'actions' },
  { name: 'askx-actions:eyedropper', category: 'actions' },
  { name: 'askx-actions:italic', category: 'actions' },
  { name: 'askx-actions:log-out', category: 'actions' },
  { name: 'askx-actions:margins', category: 'actions' },
  { name: 'askx-actions:spacing', category: 'actions' },
  { name: 'askx-actions:remove-background', category: 'actions' },
  { name: 'askx-actions:enhance-image', category: 'actions' },
  { name: 'askx-actions:enhance-quality', category: 'actions' },
  { name: 'askx-actions:bring-to-front', category: 'actions' },
  { name: 'askx-actions:send-to-back', category: 'actions' },
  { name: 'askx-actions:bring-forward', category: 'actions' },
  { name: 'askx-actions:send-backward', category: 'actions' },
  { name: 'askx-actions:align-text-left', category: 'actions' },
  { name: 'askx-actions:align-text-center', category: 'actions' },
  { name: 'askx-actions:align-text-right', category: 'actions' },
  { name: 'askx-actions:align-object-left', category: 'actions' },
  { name: 'askx-actions:align-object-horizontal-center', category: 'actions' },
  { name: 'askx-actions:align-object-right', category: 'actions' },
  { name: 'askx-actions:align-object-top', category: 'actions' },
  { name: 'askx-actions:align-object-vertical-center', category: 'actions' },
  { name: 'askx-actions:align-object-bottom', category: 'actions' },
  { name: 'askx-actions:exit-fullscreen', category: 'actions' },
  { name: 'askx-actions:flip-horizontal', category: 'actions' },
  { name: 'askx-actions:flip-vertical', category: 'actions' },
  { name: 'askx-actions:rotate-left', category: 'actions' },
  { name: 'askx-actions:rotate-right', category: 'actions' },
  { name: 'askx-actions:strikethrough', category: 'actions' },
  { name: 'askx-actions:transparency', category: 'actions' },
  { name: 'askx-actions:underline', category: 'actions' },
  { name: 'askx-navigation:arrow-up', category: 'navigation' },
  { name: 'askx-navigation:arrow-down', category: 'navigation' },
  { name: 'askx-navigation:arrow-left', category: 'navigation' },
  { name: 'askx-navigation:arrow-right', category: 'navigation' },
  { name: 'askx-navigation:chevron-down', category: 'navigation' },
  { name: 'askx-navigation:chevron-left', category: 'navigation' },
  { name: 'askx-navigation:chevron-right', category: 'navigation' },
  { name: 'askx-navigation:double-chevron-left', category: 'navigation' },
  { name: 'askx-navigation:enter', category: 'navigation' },
  { name: 'askx-status:check', category: 'status' },
  { name: 'askx-status:warning', category: 'status' },
  { name: 'askx-status:info', category: 'status' },
  { name: 'askx-status:loading', category: 'status' },
  { name: 'askx-status:lock', category: 'status' },
  { name: 'askx-status:unlock', category: 'status' },
  { name: 'askx-status:error', category: 'status' },
  { name: 'askx-status:star', category: 'status' },
  { name: 'askx-status:prohibited', category: 'status' },
  { name: 'askx-objects:agent', category: 'objects' },
  { name: 'askx-objects:skills', category: 'objects' },
  { name: 'askx-objects:layout', category: 'objects' },
  { name: 'askx-objects:layers', category: 'objects' },
  { name: 'askx-objects:model', category: 'objects' },
  { name: 'askx-objects:file', category: 'objects' },
  { name: 'askx-objects:folder', category: 'objects' },
  { name: 'askx-objects:folder-open', category: 'objects' },
  { name: 'askx-objects:file-code', category: 'objects' },
  { name: 'askx-objects:file-config', category: 'objects' },
  { name: 'askx-objects:file-html', category: 'objects' },
  { name: 'askx-objects:file-image', category: 'objects' },
  { name: 'askx-objects:file-json', category: 'objects' },
  { name: 'askx-objects:file-link', category: 'objects' },
  { name: 'askx-objects:file-markdown', category: 'objects' },
  { name: 'askx-objects:file-shell', category: 'objects' },
  { name: 'askx-objects:file-style', category: 'objects' },
  { name: 'askx-objects:file-text', category: 'objects' },
  { name: 'askx-objects:image', category: 'objects' },
  { name: 'askx-objects:video', category: 'objects' },
  { name: 'askx-objects:template', category: 'objects' },
  { name: 'askx-objects:image-analyzer', category: 'objects' },
  { name: 'askx-objects:automation', category: 'objects' },
  { name: 'askx-objects:history', category: 'objects' },
  { name: 'askx-objects:anchor', category: 'objects' },
  { name: 'askx-objects:calendar', category: 'objects' },
  { name: 'askx-objects:hand', category: 'objects' },
  { name: 'askx-objects:mini-map', category: 'objects' },
  { name: 'askx-objects:apps', category: 'objects' },
  { name: 'askx-objects:background', category: 'objects' },
  { name: 'askx-objects:elements', category: 'objects' },
  { name: 'askx-objects:resize', category: 'objects' },
  { name: 'askx-objects:text', category: 'objects' },
  { name: 'askx-objects:color-wheel', category: 'objects' },
  { name: 'askx-objects:rounded-corner', category: 'objects' },
  { name: 'askx-objects:drag-handle', category: 'objects' },
  { name: 'askx-objects:avatar-generator', category: 'objects' },
  { name: 'askx-objects:expand-image', category: 'objects' },
  { name: 'askx-objects:logo-maker', category: 'objects' },
  { name: 'askx-objects:sticker', category: 'objects' },
  { name: 'askx-objects:video-generator', category: 'objects' },
  { name: 'askx-objects:video-editor', category: 'objects' },
  { name: 'askx-objects:makeup', category: 'objects' },
  { name: 'askx-objects:music-video', category: 'objects' },
  { name: 'askx-objects:story-maker', category: 'objects' },
  { name: 'askx-objects:video-avatar', category: 'objects' },
  { name: 'askx-objects:language', category: 'objects' },
  { name: 'askx-objects:palette', category: 'objects' },
  { name: 'askx-objects:map', category: 'objects' },
  { name: 'askx-objects:pointer', category: 'objects' },
  { name: 'askx-objects:schedule', category: 'objects' },
  { name: 'askx-objects:selection', category: 'objects' },
  { name: 'askx-objects:branch', category: 'objects' },
  { name: 'askx-platforms:chatgpt-codex', category: 'platforms' },
  { name: 'askx-platforms:claude-code', category: 'platforms' },
  { name: 'askx-platforms:cursor', category: 'platforms' },
] as const satisfies ReadonlyArray<{
  name: `askx-${AskxIconCategory}:${string}`
  category: AskxIconCategory
}>

/** AskX 本地图标名称。 */
export type AskxIconName = typeof askxIconCatalog[number]['name']

/**
 * 从完整图标名称中取得对应的 SVG 文件名。
 *
 * @param name AskX 完整图标名称。
 * @returns 不含扩展名的 SVG 文件名。
 */
export function getAskxIconFileName(name: AskxIconName) {
  return name.slice(name.indexOf(':') + 1)
}
